<?php

namespace App\Filament\Widgets;

use Carbon\Carbon;
use App\Models\Review;
use App\Models\Company;
use App\Models\Location;
use Flowframe\Trend\Trend;
use Flowframe\Trend\TrendValue;
use Filament\Widgets\ChartWidget;
use Illuminate\Support\Facades\Auth;

class ReviewProgressChart extends ChartWidget
{
    protected static ?string $heading = 'Reviews Generated by Month';
    protected static ?int $sort = 2;
    protected int | string | array $columnSpan = 'full';

    protected function getData(): array
    {
       // $data = Trend::model(Review::class)
        $data = Trend::query(Review::whereIn('location_id', Location::query()->select('id')->whereIn('company_id', Company::query()->select('id')->where('users_id', Auth::id()))))
        ->between(
            start: now()->startOfYear(),
            end: now()->endOfYear(),
        )
        ->perMonth()
        ->count();
       // dd($data);
    foreach($data as $datum){
        $datum->date = Carbon::parse($datum->date)->format('M Y');
    }
    return [
        'datasets' => [
            [
                'label' => 'Reviews Generated',
                'data' => $data->map(fn (TrendValue $value) => $value->aggregate),
                'backgroundColor' => '#F2A71B',
               'borderColor' => '#282828',
            ],
        ],
        'labels' => $data->map(fn (TrendValue $value) => $value->date),
    ];
    }

    protected function getType(): string
    {
        return 'bar';
    }
}
